### ISSUE TITLE
Add test-runner for testing input/output of CLI apps

### ISSUE THREAD

**Issue by HenningCash** [code-freak/code-freak#189]
Apart from the specific (unit-)testing frameworks for each language we need a common way to test the input/output of compiled applications.

"Input" in this regard could be either a simple parameter, `stdin` or input to interactive questions like "please enter a formula" (see [expect](https://en.wikipedia.org/wiki/Expect)).

Testing output could be done by checking the exit-code and matching the textual output against a RegEx.

Because this testing method does not depend on any language-specific capabilities it could be implemented fully in Code FREAK's server-side code by starting a container based on a configurable image and specified input/output like:
```yaml
evaluation:
  - step: io
    options:
      image: gcc
      project-path: /code
      before_script: gcc -o main main.c
      tests:
      # interactive tests
      - cmd: ./main
         input:
            "number of apples": 1.5
            "number of melons": 2
         output: "^.*13.5(?:EUR|€)$"
      # argument based input
      - cmd: ./main --apples=1.5 --melons=2
         output: "^.*13.5(?:EUR|€)$"
      # stdin based input
      - cmd: ./main --stdin
        stdin: >
           {
              "apples": 1.5,
              "melons": 2
           }
        output: "^.*13.5(?:EUR|€)$"
```
